import io
import json
import zipfile
from typing import Any

import yaml

from app.models import ArtifactRun, ForgeSession
from app.schemas import ApiField, ArtifactSet


def _schema_for_field(field: ApiField) -> dict[str, Any]:
    mapping = {
        "string": {"type": "string"},
        "number": {"type": "number"},
        "integer": {"type": "integer"},
        "boolean": {"type": "boolean"},
        "object": {"type": "object"},
        "array": {"type": "array", "items": {}},
    }
    schema = dict(mapping[field.type])
    schema["description"] = field.description
    return schema


def build_openapi(artifacts: ArtifactSet, title: str) -> dict[str, Any]:
    paths: dict[str, Any] = {}
    for endpoint in artifacts.api_contract.endpoints:
        operation: dict[str, Any] = {
            "summary": endpoint.summary,
            "responses": {
                "200": {
                    "description": "Successful response",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    field.field: {
                                        "type": field.type,
                                        "description": field.description,
                                    }
                                    for field in endpoint.response_200
                                },
                            }
                        }
                    },
                }
            },
        }
        if endpoint.request_body:
            operation["requestBody"] = {
                "required": any(field.required for field in endpoint.request_body),
                "content": {
                    "application/json": {
                        "schema": {
                            "type": "object",
                            "required": [
                                field.field for field in endpoint.request_body if field.required
                            ],
                            "properties": {
                                field.field: _schema_for_field(field)
                                for field in endpoint.request_body
                            },
                        }
                    }
                },
            }
        for error in endpoint.error_codes:
            operation["responses"][str(error.code)] = {"description": error.meaning}
        paths.setdefault(endpoint.path, {})[endpoint.method.lower()] = operation

    return {
        "openapi": "3.0.3",
        "info": {
            "title": f"{title} API scaffold",
            "version": "1.0.0",
            "description": "Generated by Forge. Human review required before implementation.",
        },
        "servers": [{"url": artifacts.api_contract.base_path}],
        "paths": paths,
    }


def openapi_yaml(artifacts: ArtifactSet, title: str) -> str:
    return yaml.safe_dump(build_openapi(artifacts, title), sort_keys=False, allow_unicode=True)


def mermaid_state_machine(artifacts: ArtifactSet) -> str:
    sm = artifacts.state_machine
    lines = ["stateDiagram-v2", f"    [*] --> {sm.initial_state}"]
    for transition in sm.transitions:
        label = transition.event
        if transition.condition:
            label += f" [{transition.condition}]"
        lines.append(f"    {transition.from_state} --> {transition.to} : {label}")
    for terminal in sm.terminal_states:
        lines.append(f"    {terminal} --> [*]")
    return "\n".join(lines) + "\n"


def json_bundle(session: ForgeSession, run: ArtifactRun) -> str:
    payload = {
        "schema_version": "1.0",
        "session": {
            "id": session.id,
            "feature_name": session.feature_name,
            "feature_description": session.feature_description,
            "business_objective": session.business_objective,
            "primary_actor": session.primary_actor,
            "data_inputs_outputs": session.data_inputs_outputs,
            "downstream_dependencies": session.downstream_dependencies,
            "edge_cases": session.edge_cases,
            "compliance_context": session.compliance_context,
            "domain_pack": session.domain_pack,
        },
        "run": {
            "id": run.id,
            "provider": run.provider,
            "model": run.model,
            "prompt_version": run.prompt_version,
            "created_at": run.created_at.isoformat(),
            "latency_ms": run.latency_ms,
        },
        "artifacts": run.artifacts,
    }
    return json.dumps(payload, indent=2, ensure_ascii=False)


def export_zip(session: ForgeSession, run: ArtifactRun, artifacts: ArtifactSet) -> bytes:
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("forge-artifacts.json", json_bundle(session, run))
        archive.writestr("openapi.yaml", openapi_yaml(artifacts, session.feature_name))
        archive.writestr("state-machine.mmd", mermaid_state_machine(artifacts))
    return buffer.getvalue()
